# Time to slice and dice

Install the Transformers, Datasets, and Evaluate libraries to run this notebook.

In [74]:
!pip install datasets evaluate transformers[sentencepiece]

Requirement already satisfied: datasets in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (4.8.4)
Requirement already satisfied: evaluate in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (0.4.6)
Requirement already satisfied: transformers[sentencepiece] in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (5.4.0)
Requirement already satisfied: filelock in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (2.4.3)
Requirement already satisfied: pyarrow>=21.0.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (2.33.1)
Requirement already satisfied: httpx<1.0.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (1.8.0)
Requirement already satisfied: packaging in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from transformers[sentencepiece]) (2026.3.32)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from transformers[sentencepiece]) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from transformers[sentencepiece]) (0.7.0)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from transformers[sentencepiece]) (0.2.1)
Requirement already satisfied: protobuf in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from transformers[sentencepiece]) (7.34.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

In [75]:
!wget "https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip"
!unzip drugsCom_raw.zip

'wget' is not recognized as an internal or external command,
operable program or batch file.
'unzip' is not recognized as an internal or external command,
operable program or batch file.

In [76]:
from datasets import load_dataset

data_files = {"train": "./data/drugsComTrain_raw.tsv", "test": "./data/drugsComTest_raw.tsv"}
# \t is the tab character in Python
drug_dataset = load_dataset("csv", data_files=data_files, delimiter="\t")

In [77]:
drug_sample = drug_dataset["train"].shuffle(seed=42).select(range(1000))
# Print the first few examples of the dataset
drug_sample[:3]

{'Unnamed: 0': [87571, 178045, 80482],
 'drugName': ['Naproxen', 'Duloxetine', 'Mobic'],
 'condition': ['Gout, Acute', 'ibromyalgia', 'Inflammatory Conditions'],
 'review': ['"like the previous person mention, I&#039;m a strong believer of aleve, it works faster for my gout than the prescription meds I take. No more going to the doctor for refills.....Aleve works!"',
  '"I have taken Cymbalta for about a year and a half for fibromyalgia pain. It is great\r\nas a pain reducer and an anti-depressant, however, the side effects outweighed \r\nany benefit I got from it. I had trouble with restlessness, being tired constantly,\r\ndizziness, dry mouth, numbness and tingling in my feet, and horrible sweating. I am\r\nbeing weaned off of it now. Went from 60 mg to 30mg and now to 15 mg. I will be\r\noff completely in about a week. The fibro pain is coming back, but I would rather deal with it than the side effects."',
  '"I have been taking Mobic for over a year with no side effects other than an elevated blood pressure.  I had severe knee and ankle pain which completely went away after taking Mobic.  I attempted to stop the medication however pain returned after a few days."'],
 'rating': [9.0, 3.0, 10.0],
 'date': ['September 2, 2015', 'November 7, 2011', 'June 5, 2013'],
 'usefulCount': [36, 13, 128]}

In [78]:
for split in drug_dataset.keys():
    assert len(drug_dataset[split]) == len(drug_dataset[split].unique("Unnamed: 0"))

In [79]:
drug_dataset = drug_dataset.rename_column(
    original_column_name="Unnamed: 0", new_column_name="patient_id"
)
drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

In [80]:
def lowercase_condition(example):
    return {"condition": example["condition"].lower()}


drug_dataset.map(lowercase_condition)

Map:   0%|          | 30/161297 [00:00<?, ? examples/s]

AttributeError: 'NoneType' object has no attribute 'lower'

In [ ]:
def filter_nones(x):
    return x["condition"] is not None

In [ ]:
(lambda x: x * x)(3)

9

In [ ]:
(lambda base, height: 0.5 * base * height)(4, 8)

16.0

In [ ]:
drug_dataset = drug_dataset.filter(lambda x: x["condition"] is not None)

Filter: 100%|██████████| 161297/161297 [00:00<00:00, 181373.37 examples/s]
Filter: 100%|██████████| 53766/53766 [00:00<00:00, 177929.28 examples/s]

In [ ]:
drug_dataset = drug_dataset.map(lowercase_condition)
# Check that lowercasing worked
drug_dataset["train"]["condition"][:3]

Map: 100%|██████████| 160398/160398 [00:12<00:00, 13359.74 examples/s]
Map: 100%|██████████| 53471/53471 [00:03<00:00, 13743.11 examples/s]

['left ventricular dysfunction', 'adhd', 'birth control']

In [ ]:
def compute_review_length(example):
    return {"review_length": len(example["review"].split())}

In [ ]:
drug_dataset = drug_dataset.map(compute_review_length)
# Inspect the first training example
drug_dataset["train"][0]

Map: 100%|██████████| 160398/160398 [00:09<00:00, 17732.35 examples/s]
Map: 100%|██████████| 53471/53471 [00:03<00:00, 17337.56 examples/s]

{'patient_id': 206461,
 'drugName': 'Valsartan',
 'condition': 'left ventricular dysfunction',
 'review': '"It has no side effect, I take it in combination of Bystolic 5 Mg and Fish Oil"',
 'rating': 9.0,
 'date': 'May 20, 2012',
 'usefulCount': 27,
 'review_length': 17}

In [ ]:
drug_dataset["train"].sort("review_length")[:3]

{'patient_id': [111469, 13653, 53602],
 'drugName': ['Ledipasvir / sofosbuvir',
  'Amphetamine / dextroamphetamine',
  'Alesse'],
 'condition': ['hepatitis c', 'adhd', 'birth control'],
 'review': ['"Headache"', '"Great"', '"Awesome"'],
 'rating': [10.0, 10.0, 10.0],
 'date': ['February 3, 2015', 'October 20, 2009', 'November 23, 2015'],
 'usefulCount': [41, 3, 0],
 'review_length': [1, 1, 1]}

In [ ]:
drug_dataset = drug_dataset.filter(lambda x: x["review_length"] > 30)
print(drug_dataset.num_rows)

Filter: 100%|██████████| 138514/138514 [00:02<00:00, 62485.38 examples/s]
Filter: 100%|██████████| 46108/46108 [00:00<00:00, 63927.18 examples/s]

{'train': 138514, 'test': 46108}

In [ ]:
import html

text = "I&#039;m a transformer called BERT"
html.unescape(text)

"I'm a transformer called BERT"

In [ ]:
drug_dataset = drug_dataset.map(lambda x: {"review": html.unescape(x["review"])})

Map: 100%|██████████| 138514/138514 [00:11<00:00, 11878.30 examples/s]
Map: 100%|██████████| 46108/46108 [00:03<00:00, 11925.00 examples/s]

In [ ]:
new_drug_dataset = drug_dataset.map(
    lambda x: {"review": [html.unescape(o) for o in x["review"]]}, batched=True
)

Map: 100%|██████████| 138514/138514 [00:00<00:00, 486753.77 examples/s]
Map: 100%|██████████| 46108/46108 [00:00<00:00, 461138.71 examples/s]

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")


def tokenize_function(examples):
    return tokenizer(examples["review"], truncation=True)

c:\Users\COM\miniconda3\envs\hf-llm\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\COM\.cache\huggingface\hub\models--bert-base-cased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
%time tokenized_dataset = drug_dataset.map(tokenize_function, batched=True)

Map: 100%|██████████| 138514/138514 [00:08<00:00, 16961.38 examples/s]
Map: 100%|██████████| 46108/46108 [00:02<00:00, 16475.46 examples/s]

CPU times: total: 1min 8s
Wall time: 11.1 s

In [ ]:
# use_fast = false, num_proc = 8
slow_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)

def slow_tokenize_function(examples, slow_tokenizer):
    return slow_tokenizer(examples["review"], truncation=True)


tokenized_dataset = drug_dataset.map(slow_tokenize_function, batched=True, num_proc=8, fn_kwargs={"slow_tokenizer": slow_tokenizer})

Map (num_proc=8): 100%|██████████| 161297/161297 [00:12<00:00, 12636.54 examples/s]
Map (num_proc=8): 100%|██████████| 53766/53766 [00:11<00:00, 4744.14 examples/s]

In [81]:
# use_fast = false, num_proc = 1
slow_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)

def slow_tokenize_function(examples, slow_tokenizer):
    return slow_tokenizer(examples["review"], truncation=True)


tokenized_dataset = drug_dataset.map(slow_tokenize_function, batched=True, num_proc=1, fn_kwargs={"slow_tokenizer": slow_tokenizer})

In [ ]:
# use_fast = true, num_proc = 8
slow_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=True)

def slow_tokenize_function(examples, slow_tokenizer):
    return slow_tokenizer(examples["review"], truncation=True)


tokenized_dataset = drug_dataset.map(slow_tokenize_function, batched=True, num_proc=8, fn_kwargs={"slow_tokenizer": slow_tokenizer})

In [65]:
# use_fast = true, num_proc = 1
slow_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=True)

def slow_tokenize_function(examples, slow_tokenizer):
    return slow_tokenizer(examples["review"], truncation=True)


tokenized_dataset = drug_dataset.map(slow_tokenize_function, batched=True, num_proc=1, fn_kwargs={"slow_tokenizer": slow_tokenizer})

In [101]:
def tokenize_and_split(examples):
    return tokenizer(
        examples["review"],
        truncation=True,
        max_length=128,
        return_overflowing_tokens=True,
    )

In [105]:
result = tokenize_and_split(drug_dataset["train"][:2])
[len(inp) for inp in result["input_ids"]]

[25, 128, 49]

In [103]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)

Map:   0%|          | 0/161297 [00:00<?, ? examples/s]

ArrowInvalid: Column 7 named input_ids expected length 1000 but got length 1441

In [106]:
tokenized_dataset = drug_dataset.map(
    tokenize_and_split, batched=True, remove_columns=drug_dataset["train"].column_names
)

In [107]:
len(tokenized_dataset["train"]), len(drug_dataset["train"])

(236136, 161297)

In [108]:
def tokenize_and_split(examples):
    result = tokenizer(
        examples["review"],
        truncation=True,
        max_length=128,
        return_overflowing_tokens=True,
    )
    # Extract mapping between new and old indices
    sample_map = result.pop("overflow_to_sample_mapping")
    for key, values in examples.items():
        result[key] = [values[i] for i in sample_map]
    return result

In [109]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)
tokenized_dataset

Map: 100%|██████████| 161297/161297 [00:32<00:00, 4957.53 examples/s]
Map: 100%|██████████| 53766/53766 [00:10<00:00, 5120.70 examples/s]

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 236136
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 78728
    })
})

In [110]:
drug_dataset.set_format("pandas")

In [111]:
drug_dataset["train"][:3]

,patient_id,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17

In [112]:
train_df = drug_dataset["train"][:]

In [ ]:
frequencies = (
    train_df["condition"]
    .value_counts()
    .to_frame()
    .reset_index()
    .rename(columns={"index": "condition", "condition": "frequency"})
)
frequencies.head()

                                       frequency  count
0                                  Birth Control  28788
1                                     Depression   9069
2                                           Pain   6145
3                                        Anxiety   5904
4                                           Acne   5588
..                                           ...    ...
879                                 Tinea Barbae      1
880                Acute Nonlymphocytic Leukemia      1
881  62</span> users found this comment helpful.      1
882  92</span> users found this comment helpful.      1
883                                  Neutropenia      1

[884 rows x 2 columns]

In [114]:
from datasets import Dataset

freq_dataset = Dataset.from_pandas(frequencies)
freq_dataset

Dataset({
    features: ['frequency', 'count'],
    num_rows: 884
})

In [116]:
drug_dataset.reset_format()

In [117]:
drug_dataset_clean = drug_dataset["train"].train_test_split(train_size=0.8, seed=42)
# Rename the default "test" split to "validation"
drug_dataset_clean["validation"] = drug_dataset_clean.pop("test")
# Add the "test" set to our `DatasetDict`
drug_dataset_clean["test"] = drug_dataset["test"]
drug_dataset_clean

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 129037
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 32260
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

In [118]:
drug_dataset_clean.save_to_disk("./data/drug-reviews")

Saving the dataset (1/1 shards): 100%|██████████| 129037/129037 [00:00<00:00, 168387.89 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 32260/32260 [00:00<00:00, 172043.05 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 53766/53766 [00:00<00:00, 1623525.57 examples/s]

In [119]:
from datasets import load_from_disk

drug_dataset_reloaded = load_from_disk("./data/drug-reviews")
drug_dataset_reloaded

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 129037
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 32260
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

In [120]:
for split, dataset in drug_dataset_clean.items():
    dataset.to_json(f"./data/drug-reviews-{split}.jsonl")

Creating json from Arrow format: 100%|██████████| 130/130 [00:01<00:00, 106.79ba/s]
Creating json from Arrow format: 100%|██████████| 33/33 [00:00<00:00, 104.86ba/s]
Creating json from Arrow format: 100%|██████████| 54/54 [00:00<00:00, 243.95ba/s]

In [ ]:
!head -n 1 drug-reviews-train.jsonl

{"patient_id":141780,"drugName":"Escitalopram","condition":"depression","review":"\"I seemed to experience the regular side effects of LEXAPRO, insomnia, low sex drive, sleepiness during the day. I am taking it at night because my doctor said if it made me tired to take it at night. I assumed it would and started out taking it at night. Strange dreams, some pleasant. I was diagnosed with fibromyalgia. Seems to be helping with the pain. Have had anxiety and depression in my family, and have tried quite a few other medications that haven't worked. Only have been on it for two weeks but feel more positive in my mind, want to accomplish more in my life. Hopefully the side effects will dwindle away, worth it to stick with it from hearing others responses. Great medication.\"","rating":9.0,"date":"May 29, 2011","usefulCount":10,"review_length":125}

In [122]:
data_files = {
    "train": "./data/drug-reviews-train.jsonl",
    "validation": "./data/drug-reviews-validation.jsonl",
    "test": "./data/drug-reviews-test.jsonl",
}
drug_dataset_reloaded = load_dataset("json", data_files=data_files)
drug_dataset_reloaded

Generating train split: 129037 examples [00:00, 430141.86 examples/s]
Generating validation split: 32260 examples [00:00, 364292.98 examples/s]
Generating test split: 53766 examples [00:00, 426250.76 examples/s]

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 129037
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 32260
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})